name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags-ignore:
      - '**'

jobs:

  release:

    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token

      - name: Release
        id: release
        uses: cycjimmy/semantic-release-action@v4
        with:
          branches: |
            [
              'main'
            ]
          extra_plugins: |
            @semantic-release/commit-analyzer@12.0.0
            @semantic-release/release-notes-generator@13.0.0
            @semantic-release/changelog@6.0.3
            @semantic-release/git@10.0.1
            @semantic-release/github@10.0.5
        env:
          GIT_CREDENTIALS: git:${{ secrets.PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
